### PR TITLE
Renard validator(MyValidationInterceptor) should not apply on rest enpoint that not extends renarde.Controller

### PR DESCRIPTION
**Pull request by pramoth**
I have 2 controller 
1. json rest 
2. htmx (renard controller)
when I apply @Valid on 1. I observe that MyValidationInterceptor add ConstrainViolation to validation.error event if my controller does not extends renard Controller. So I can't report error back to user like normal rest . and endpoint method get called even if validate fail (it is OK for htmx,html response)

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
Oh, nice catch. This seems like a legit use-case. Do you mind adding a note in the documentation to make it clear that validation in non-controllers will cause the endpoint to never be entered?

Probably a test would be safe too :)

**Comment by pramoth** [comment]
@FroMage the test was added.

**Comment by FroMage** [comment]
Perfect. A note in the docs? :) I can add it for you if you prefer.

**Comment by pramoth** [comment]
> Perfect. A note in the docs? :) I can add it for you if you prefer.
Yes, please! That would be great, thank you.

**Comment by FroMage** [comment]
Merged, thanks!

**Pull request merged**
